# Example configuration file for audpipe. Use whatever TOML syntax you like.
# Hostnames can be resolved using the system DNS if you like. We default to
# IPv6 as recommended for newer applications.
# 
# Only your remote details need to be specified if you don't mind using local
# defaults. I should add these to the README or something.

# [client]
# ip = "smh"
# port = 7981

[server]
ip = "jinch-thinkpad"
port = 8179

# Set some initial connection defaults here.
# The below values are default values, bear in mind.
[net]
connect_timeout_ms = 5000
handshake_timeout_ms = 3000
max_retries = 3
retry_backoff_ms = 2000
max_backoff_ms = 30000
keepalive_interval_ms = 20000
unreachable_after_failures = 3
