# Example configuration file for audpipe. Use whatever TOML syntax you like.
# Hostnames can be resolved using the system DNS if you like. We default to
# IPv6 as recommended for newer applications.
# 
# Only your remote details need to be specified if you don't mind using local
# defaults. I should add these to the README or something.

[client]
ip = "localhost"
port = 7981

[server]
ip = "localhost"
port = 8179
